<?php

namespace Neogen\CommandSchedulerBundle\Repository;

/**
 * CommandEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
